name: dlh
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  badges: ^3.0.2
  carousel_slider: ^4.2.1
  internet_connection_checker: ^1.0.0+1
  cupertino_icons: ^1.0.5
  curved_navigation_bar: ^1.0.3
  datetime_picker_formfield: ^2.0.0
  dio: ^5.0.0
  file_picker: 5.2.5
  flutter_launcher_icons: ^0.11.0
  flutter_map: any
  flutter_widget_from_html: ^0.10.0
  flutter_inappwebview: ^5.7.2+3
  flutter_svg: ^2.0.0
  fwfh_svg: ^0.8.0+1
  http: ^0.13.5
  html: ^0.15.1
  intl: ^0.18.0
  image_picker: ^0.8.6+2
  loading_animation_widget: ^1.2.0+4
  map: ^1.3.5+1
  path_provider: 2.0.12
  shared_preferences: ^2.0.17
  top_snackbar_flutter: ^3.0.0+1
  url_launcher: ^6.1.9



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_name:
   name: "DLH Kota Serang"

flutter_icons:
  image_path: "asset/siherang.png"
  image_path_android: 'asset/siherang.png'
  image_path_ios: 'asset/s1.png'
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/
    - asset/img/
    - asset/icon/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
